name: CBT Student pipeline
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build & Push to repository
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ secrets.DOCKER_USERNAME }}/cbt-admin
      TAGS: ${GITHUB_REF##*/}
    steps:
      - uses: actions/checkout@v3
        name: Checkout branch

      - name: Build and Push image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker image build -t ${{ env.IMG_NAME }}:${{ env.TAGS }}-v1 .
          docker push ${{ env.IMG_NAME }}:${{ env.TAGS }}-v1
  deploy:
    name: Deploy to development server
    needs: build
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ secrets.DOCKER_USERNAME }}/cbt-admin
      TAGS: main
      CONTAINER_NAME: cbt-admin-dev-v1
    steps:
      - name: Executing deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.USER_SERVER }}
          password: ${{ secrets.PASSWORD_SERVER }}
          port: 22
          script: |
            docker pull ${{ env.IMG_NAME }}:${{ env.TAGS }}-v1
            docker rm -f ${{ env.CONTAINER_NAME }} || true
            docker run -d -p 3001:80 --name ${{ env.CONTAINER_NAME }} ${{ env.IMG_NAME }}:${{ env.TAGS }}-v1
