name: CBT Student pipeline
on:
  push:
    branches:
      - 'production'
jobs:
  build:
    name: Build & Push to repository
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ secrets.DOCKER_USERNAME }}/cbt-admin
      TAGS: ${GITHUB_REF##*/}
    steps:
      - uses: actions/checkout@v3
        name: Checkout branch

      - name: Build and Push image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker image build -t ${{ env.IMG_NAME }}:${{ env.TAGS }}-v1 .
          docker push ${{ env.IMG_NAME }}:${{ env.TAGS }}-v1